[agent]
  interval = "1s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "1s"
  flush_jitter = "0s"
  precision = "0s"
  hostname = ""
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://127.0.0.1:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "${INFLUX_ORG}"
  bucket = "${INFLUX_BUCKET}"
  timeout = "1s"
  user_agent = "telegraf"

[[processors.converter]]
  [processors.converter.fields]
    float = ["Temperatura CPU"]

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = false
  core_tags = false

[[inputs.mem]]

[[inputs.disk]]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.system]]

# Standard SNMP host monitoring
[[inputs.snmp]]
   agents = ["udp://localhost"]
   name = "snmp"
   timeout = "1s"
   version = 2
   community = "${SNMP_COMMUNITY}"

  [[inputs.snmp.field]]
     oid = "RFC1213-MIB::sysName.0"
     name = "sysName"
     is_tag = true

  [[inputs.snmp.table]]
      name = "hrStorageTable"
      oid = "1.3.6.1.2.1.25.2.3"

  [[inputs.snmp.table.field]]
      name = "NameStorage"
      oid = "1.3.6.1.2.1.25.2.3.1.3"
      is_tag = true

  [[inputs.snmp.field]]
      name = "in_octets"
      oid = "IF-MIB::ifInOctets.30"

  [[inputs.snmp.field]]
      name = "out_octets"
      oid = "IF-MIB::ifOutOctets.30"

# Custom SNMP Agent: Hardware Telemetry
[[inputs.snmp]]
   agents = ["${REMOTE_AGENT_IP}:162"]
   name = "hardware_telemetry"
   timeout = "1s"
   version = 2
   community = "${SNMP_COMMUNITY}"

  [[inputs.snmp.field]]
      name = "Temperatura CPU"
      oid = "1.3.6.1.4.1.12345.1.0"

  [[inputs.snmp.field]]
      name = "Potencia CPU"
      oid = "1.3.6.1.4.1.12345.1.1"

  [[inputs.snmp.field]]
      name = "Carga CPU"
      oid = "1.3.6.1.4.1.12345.1.2"

  [[inputs.snmp.field]]
      name = "Carga RAM"
      oid = "1.3.6.1.4.1.12345.1.3"

  [[inputs.snmp.field]]
      name = "Uso Disco Duro"
      oid = "1.3.6.1.4.1.12345.1.6"
